[package]
name = "lock-key-indicator"
version = "0.1.0"
authors = ["Stan Drozd (nixie-dust) <drozdziak1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systray = "0.4.0"
lock_keys = "1.0.0"
